export const SET_BACKEND_PAYMENT_PAYPAL_EXPRESS = 'SET_BACKEND_PAYMENT_PAYPAL_EXPRESS'
export const SET_PAYPAL_EXPRESS_TOKEN = 'SET_PAYPAL_EXPRESS_TOKEN'
export const SET_PAYPAL_MESSAGE = 'SET_PAYPAL_MESSAGE'
